import esbuild from "esbuild";
import process from "process";
// We'll use a simple copy function instead of the plugin
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/state",
      "@codemirror/view",
      "child_process",
      "fs",
      "path",
      "net",
      "crypto",
      "os"
    ],
    format: "cjs",
    watch: !prod,
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    define: {
      "process.env.NODE_ENV": prod ? "\"production\"" : "\"development\"",
    },
  })
  .then(() => {
    // Copy manifest.json and styles.css
    fs.copyFileSync("manifest.json", "main.js.manifest");
    fs.copyFileSync("styles.css", "main.js.css");
    console.log("Build completed successfully!");
  })
  .catch((error) => {
    console.error("Build failed:", error);
    process.exit(1);
  });
